language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
notifications:
  email: 
    - yoav@yoavram.com
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - export MPLBACKEND=agg
  - conda config --add channels conda-forge
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - conda install -q python=$TRAVIS_PYTHON_VERSION
  - conda update -q conda pip
  - pip install nose codecov | cat
# Install packages
install: 
  - pip install .
script: 
  - myzcat --version
  - nosetests tests --with-coverage --cover-package=myzcat